### ISSUE TITLE
Pickling a plot

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#1]
In the past I thought it would be cool to save all data that appears in a plot in a human readable file alongside the pdf (or whatever) of the plot itself.

It occurred to me: would it possible to pickle the whole plot object as well? Right up to before you do a `plt.savefig()` or a `plt.show()`? [SE](http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object) says it might be.

I think it would be nice because then I could unpickle it, and make any small changes I wanted to it, little changes that might be tricky within the GUI. Or correct things I make mistakes on when I used the GUI. 

A good idea or not?

PS everything looks great so far.

**Comment by michaelhb** [comment]
Interesting idea - you'd be able to load the plot up in a python console and manipulate it directly.

Will look into once I'm done with the config stuff!

**Comment by andrewfowlie** [comment]
OK, see http://matplotlib.org/users/whats_new.html#figures-are-picklable

Pickling in matplotlib is described as experimental.

**Comment by michaelhb** [comment]
I've added a "pickle plot" button in the develop branch. For some reason drawing the plot messes up the pickling, so the trick was to re-create the plot just before pickling. 

On my system the following code shows a window containing the pickled plot:

``` python
import matplotlib.pyplot as plt
import pickle as pl
import numpy as np

# Load figure from disk and display
fig_handle = pl.load(open('example.pkl','rb'))
plt.show()
```

**Comment by andrewfowlie** [comment]
Great. I think this is going to be useful. Do you think it should be a separate button? Or should saving a figure always make a pkl? Maybe I could write 3 tick-boxes:
- Save plot
- Save pickle
- Save stats

Which would change the behaviour of a single save button? What's the best method?

**Comment by michaelhb** [comment]
I think tick-boxes is probably better from a workflow perspective - less clicks if you're exporting a bunch of plots. 

Also - how do you think the statistics bit should work? IE assuming we are talking information specific to each plot type, it might be good to mock up what each summary type should look like in terms of rows / columns / etc.

**Comment by andrewfowlie** [comment]
Agreed on tick-boxes. I'll think about the summary information per plot. I've just pushed 2 commits to my branch: one that fixes a small bug, and second that overhauls summary.py, beginning to turn it into something that can be used more generally to summarize the plots.

I think the per-plot summary should contain:
- .txt file name and path
- date?
- number of bins
- bin limits
- alpha 
- posterior mean (for x and y if 2D. Independent of binning)
- best-fit point  (for x and y if 2D. Independent of binning)
- If a 1D plot, 1D credible regions for each alpha (dependent on binning)
- if a 1D plot, 1D confidence intervals for each alpha (dependent on binning, and not contiguous, so a big list)

NB that this isn't to preserve data, so it doesn't have to be complete. It's just about being able to find the exact number that's plotted without having to carefully read the axis.

**Comment by michaelhb** [comment]
I've made a start - tick boxes are above the "save plot" button. The summary file consists of generic info (date, file names, number of bins, bin limits, alpha), followed by any plot-specific items. EG for the default 1D plot you also get the best-fit point, posterior mean, upper/lower credible regions, and confidence intervals. I'll add in specific items for the rest of the plots tomorrow.

**Comment by michaelhb** [comment]
PS: What do you think of my idea for style configuration here: https://github.com/michaelhb/superplot/issues/12 ?

**Comment by andrewfowlie** [comment]
That's great!

**Comment by michaelhb** [comment]
OK - I've added plot-specific stuff.
- Best-fit and posterior mean points for everything.
- Credible regions, confidence intervals for the 1D standard plot.
- Boundaries of the filled in (excluded?) regions for the chisq plot.

When you've got time, could you check over the summaries and make sure I've implemented them correctly? Or if there is anything missing that you'd like in there, let me know & I'll add it.

Cheers!
