### ISSUE TITLE
Idea for plot style configuration

### ISSUE THREAD

**Issue by michaelhb** [michaelhb/superplot#12]
One issue with the way style sheets are now implemented is that things like line width are set globally. This causes some issues - for instance, we probably want to draw contours at thickness two, but other lines at thickness four. 

One way we could manage this is creating a "styles" folder containing default.mplstyle, and a style sheet for each plot type. This would allow any default option to be overridden for a specific plot type. Not hard to implement:

``` python
plt.style.use(["./styles/default.mplstyle", "./styles/<some plot>.mplstyle"])
```

should do it. 

Does this sound like a good way of doing things?

**Comment by andrewfowlie** [comment]
I think this is a great idea. I did indeed set all line-widths globally including the contour lines. I thought even if `lw=3` was a slightly poor choice for contour lines, it was better to have it easily configurable than hard-coded.

Multiple style sheets can probably make it very configurable and have good defaults.

**Comment by michaelhb** [comment]
Done. There is now a styles/ folder with default.mplstyle and a style sheet for each plot. I've reduced the line thickness in the contour plots so it looks like it used to, but it should be possible to change all kinds of things on a per-plot basis now.

Note that the style sheets can be edited while the app is running as they are reloaded every time a plot is made.
