### ISSUE TITLE
Y-axis label on 1D plot

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#14]
The y-axis label for the 1D plot should be blank or say something like "probability density". At the moment, however, it puts whatever would be on the y-axis if it were a 2D plot.

**Comment by michaelhb** [comment]
Done - have set it to "Probability Density".

**Comment by andrewfowlie** [comment]
Ah, I think we might have a collision - I've made a few commits, one of which fixes this. See https://github.com/innisfree/superplot/commit/f4560265ea477a7c5725139bd7d1459df9d863f6

**Comment by michaelhb** [comment]
No worries - I've merged and kept your version.
