### ISSUE TITLE
1 and 2\sigma internals flipped on 1D plots

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#15]
I think my re-organization of the credible regions and confidence intervals changed the order of 1 and 2\sigma confidence intervals/credible regions.

As a result, what is called 1\sigma is actually 2\sigma and vice-versa.

This happens because I've done `for aa in opt.alpha`, and alpha is in ascending order which corresponds to 2\sigma then 1\sigma, whereas the schemes go 1\sigma then 2\sigma

The 2D plots are immune to this sort of error as they have `levels = sort(levels)`.

**Comment by andrewfowlie** [comment]
I thought about fixing this with `_defaults["alpha"] = sorted(np.array(_defaults["alpha"]), reverse=True)` in the plot_options.py, but this doesn't work well.

It means that 2\sigma is plotted on top of 1\sigma, which hides 1\sigma confidence intervals and credible regions as 2\sigma regions contain 1\sigma regions.

Probably a combination of `_defaults["alpha"] = sorted(np.array(_defaults["alpha"]))` so that the order is fixed and reverse statements on the for loops where 1D confidence intervals/credible regions are calculted would work best, e.g. 

```
    conf_intervals = [one_dim.conf_interval(prof_data.prof_chi_sq, prof_data.bin_centers, alpha=aa) for aa in reversed(opt.alpha)]
```

**Comment by andrewfowlie** [comment]
I think I've fixed this in my fork with https://github.com/innisfree/superplot/commit/e9d863bb5a4fcb70138f25c5ad6f080b50d56b89

**Comment by michaelhb** [comment]
Heh, I was about to commit the exact same fix. 

I think it would be a good idea to assign issues to ourselves when we start working on a bug / feature so that we don't end up working on the same thing.

**Comment by michaelhb** [comment]
Also - I've added you as a collaborator to my fork. Feel free to commit to develop which is my main working branch. I think that would be cleaner than working across two forks anyway.

**Comment by andrewfowlie** [comment]
OK, will do. I've finished working on this for today now.
