### ISSUE TITLE
Errors if text file has fewer than 5 columns (i.e. not enough data for x, y and z)

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#16]
If you try a data file with less than 5 columns (i.e. not enough data for x, y and z), e.g. `posterior weight, chi-squared, x-data`, you get errors about it not being able to set text boxes for the y-data and z-data

```
  File "super_gui.py", line 491, in _cz
    self.ztext.set_text(self.labels[self.zindex])
  KeyError: -1
```

**Comment by michaelhb** [comment]
I think this is working now - I'm able to load gaussian_.txt with no info file make plots etc.
