### ISSUE TITLE
Problem wit git

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#17]
Hello,

Sorry, I've made a bit of a mess of the repository.  I did

```
git clone https://github.com/michaelhb/superplot.git develop
git pull https://github.com/innisfree/superplot.git
git push
```

This seems to have pushed to https://github.com/michaelhb/superplot.git master

How can I fix this? I wanted to integrate my changes then just work on the develop branch of your fork.

**Comment by andrewfowlie** [comment]
Ah, I was missing a `-b` for the branch. It never cloned the develop branch which is why it pushed to master...

```
git clone https://github.com/michaelhb/superplot.git -b develop
```

Let me do it properly this time. It's confusing because if you leave out the `-b` you get the master branch but in a folder called `develop`...

OK, it's finished. No problem, except the master branch now has a mixture of commits.

**Comment by michaelhb** [comment]
No worries, looks good now. RE master - it'll be a fast forward merge when we are ready to release, so no problems there.
