### ISSUE TITLE
pip install command

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#18]
A few bugs with the pip installation. My first attempt:

```
 andrew@andrew-laptop:~$ sudo pip install --index=https://testpypi.python.org/pypi superplot
 Downloading/unpacking superplot
   Could not find a version that satisfies the requirement superplot (from versions: 2.0.dev0, 2.0.dev0)
   Some externally hosted files were ignored (use --allow-external to allow).
 Cleaning up...
 No distributions matching the version for superplot
 Storing debug log for failure in /home/andrew/.pip/pip.log
```

I think this is related to the [pre-release settings in pip](http://pip.readthedocs.org/en/1.4.1/logic.html#pre-release-versions).

```
 sudo pip install --pre --index=https://testpypi.python.org/pypi superplot
 Downloading/unpacking superplot
   Downloading superplot-2.0.dev0-py2-none-any.whl
 Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from superplot)
 Requirement already satisfied (use --upgrade to upgrade): pandas in /usr/local/lib/python2.7/dist-packages (from superplot)
 Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python2.7/dist-packages (from superplot)
 Downloading/unpacking simpleyaml (from superplot)
   Could not find any downloads that satisfy the requirement simpleyaml (from superplot)
   Some externally hosted files were ignored (use --allow-external simpleyaml to allow).
 Cleaning up...
 No distributions at all found for simpleyaml (from superplot)
 Storing debug log for failure in /home/andrew/.pip/pip.log
```

Anyhow, installing it by hand, `pip install simpleyaml` gives me the same problem with a package called `appdirs`, which I also installed by hand.  

Do we need something like the `--allow-all-external` argument to make sure it does this automatically? Unfortunately, this still gives me,  `Some insecure and unverifiable files were ignored (use --allow-unverified simpleyaml to allow).` There is no `allow-all-unverified` argument!

**Comment by michaelhb** [comment]
Agreed on the first issue - I think I forgot to clear my pip cache when I was testing. I get the same thing with "--no-cache". In any case the flag won't be required once we do a proper release.

RE appdirs and simpleyaml - I think pip is trying to fetch them from pypi test, which doesn't have those packages. I thought it might be possible to force pip to get them from the main repo by adding "--index=https://pypi.python.org/pypi" to requirements.txt, although that doesn't seem to work. But I'm pretty sure we won't have this issue once we do a release on pypi proper.

**Comment by andrewfowlie** [comment]
OK, sure, so this stuff won't happen when we release the proper version? If so, no problem.
