### ISSUE TITLE
Gaussian probabilities

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#19]
At the moment, in the yaml we have `alpha: [0.05, 0.32]`. These approximately correspond to 2-tail Gaussian 2- and 1-sigma probabilities. We should hard-code a few more digits (https://en.wikipedia.org/wiki/Normal_distribution#Standard_deviation_and_tolerance_intervals), e.g. `alpha: [0.045500263896, 0.31731050786]`

**Comment by michaelhb** [comment]
Done - I've updated config.yml with the provided values.

**Comment by andrewfowlie** [comment]
Thanks  - I wasn't sure what branch to make the change on.
