### ISSUE TITLE
Plot options

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#2]
Hello, 

Let me start building a full list of plot options. In addition to those in `Appearance.py` (the format of which etc could change), inside the `yaml` options file there should be options to turn on/off bits of a plot. E.g. you might want to remove the best-fit point.
# All
- Best-fit
- Posterior mean
- ~~LaTeX labels or not (+error handling at the right point)~~
- Legend position (in `PlotMod.py`). There are other legend options, but I think position is the only really important one.
- Figure size (in `PlotMod.py`)
- Line thickness (in `PlotMod.py`)
- Plot a grid (in `PlotMod.py`)
- Whether to write a *.txt summary 
- Whether to write a pickle of the plot
# 1D only
- Confidence intervals
- Credible regions
- Profile likelihood
- Posterior PDF

**Comment by michaelhb** [comment]
Cool - this will be useful!

**Comment by michaelhb** [comment]
I've added a combo box to the GUI that allows the legend position to be selected, or the legend to be turned off. The options are:

"best", "upper right", "lower left", "lower right", "right", "center left",
"center right", "lower center", "upper center", "center", "no legend"

**Comment by michaelhb** [comment]
OK - I think everything here is done:
- Legend can be re-positioned or turned off with a combo box.
- Figure size, line thickness and grid can be configured via .mplstyle files.
- Text summaries, pickle file and PDF export can all be toggled on/off.
- Best-fit, posterior mean, confidence intervals, credible regions, profile likelihood and posterior PDF can now be toggled on/off where applicable using checkboxes above the "make plot" button.

When you've got time, can you test out the new features and make sure they're working as you expect?

Cheers!

**Comment by andrewfowlie** [comment]
Thanks, everything is working. I changed the default toggles for saving plots etc in my fork.
