### ISSUE TITLE
Informative error message if matplotlib < 1.4

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#22]
At the moment, with an old version of matplotlib (<1.4), you see an error

```
AttributeError: 'module' object has no attribute 'style'
```

I will make it clearer what went wrong and what should be done.

**Comment by andrewfowlie** [comment]
Something like this, perhaps? At build-time or at run-time?

```
import matplotlib
from distutils.version import StrictVersion

version = StrictVersion(matplotlib.__version__)
required_version = StrictVersion("1.4")
if version < required_version:
    raise ImportError("Superplot requires matplotlib %s. "  
                       "You are running matplotlib %s. " 
                       "Updgrade via e.g. pip install --upgrade matplotlib"
                       % (required_version, version))
```

**Comment by andrewfowlie** [comment]
I've just noticed that the fix reported by email is actually:

`pip install --force-reinstall --upgrade matplotlib`

i.e. with `--force-reinstall`. Perhaps that should be in the above and in the documentation (the command is there without that flag in the manual).

**Comment by michaelhb** [comment]
Hi,

I agree with both of your suggestions above. For redundancy I think we should have a run-time check (your snippet looks good) as well as an install time check. The install time check is just adding a version specifier to the dependencies list in setup.py: "matplotlib >= 1.4".

If you're putting a patch together, let me know when it is pushed and I'll publish a new build to PyPi. 

Also, if you'd like to be able to publish builds, let me know your PyPi user name and I'll add you as a maintainer.

Cheers!

**Comment by michaelhb** [comment]
Have implemented above / published build. Also wrapped import of GTK backend so that error message resulting from matplotlib sans GTK support is less cryptic / more helpful.
