### ISSUE TITLE
ReadTheDocs out-of-date

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#23]
My commit to the README.rst hasn't triggered a re-build of the read-the-docs documentation by the hook (it isn't the case that a re-build failed, it didn't attempt one). Don't know why. http://readthedocs.org/projects/superplot/builds/ The README was a bit out-of-date...

**Comment by michaelhb** [comment]
Ah, just checked and there was no trigger. I ran a build and set up a webhook so future builds will be automatic.

**Comment by andrewfowlie** [comment]
Great, thanks. The ReadTheDocs github hook is pretty cool!
