### ISSUE TITLE
Test/document KDE 

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#24]
I want to check the kernel density options are working as expected (and check a few other of my commits), then document the KDE in v2 of the arXiv manual. 

Once it's checked, we should release a v1.1 (i.e. a new version that includes new features, not just bug fixes) simultaneously with v2 of the manual.

**Comment by michaelhb** [comment]
No worries - let me know when you are happy with the changes. I'll run the tests on my end and do the deployment.

**Comment by andrewfowlie** [comment]
Hello,

OK, I think this is ready. I made new doctests for the KDE and I was satisfied it was reliable and that there are no important bugs. The results look good.

There are new dependencies for caching the stats functions.  See https://github.com/michaelhb/superplot/blob/master/superplot/statslib/patched_joblib.py

This was slightly more involved than I thought, because without taking extra steps, decorated functions don't have the same e.g. `__doc__` attributes as the original functions, so can't be doctested. But it's fixed now by slightly modifying the joblib Memory class.

I'm going to finish the manual and submit to a journal & arxiv in the next few days. I'll email you before I submit anything anywhere.

Andrew.

**Comment by andrewfowlie** [comment]
BTW, is it the middle of exams? If so, this has very low priority!

**Comment by michaelhb** [comment]
Hi Andrew,

Yes, it's peak exam season! Last one is on the 20th. So no time for code
review / testing on my end but if you're happy with the changes I can do a
deployment, that is a five minute task.

Also, I got confirmation that I'll be giving a spoken presentation on
Superplot at ICUR :). I've got a rough idea of what to talk about but if
it's OK I'd appreciate your feedback on the drafts (I also have to write an
article) that I'll put together over the break.

Cheers,
Michael

**Comment by michaelhb** [comment]
I've tested the KDE functionality on Windows and Linux. No problems on linux. On Windows I had no trouble using KDE smoothing in the GUI, but the doctest for statslib.one_dim throws up an out of memory error. Probably not much to worry about.

I've also moved super_command into the superplot package and added hooks so that setup.py installs command line scripts in appropriate places when run.

**Comment by andrewfowlie** [comment]
Hello, 

The conference is all over. Great, so we should release a new version, I think. Then submit a new version of the manual (this is more or less ready).

Andrew.

**Comment by michaelhb** [comment]
Hi,

Agreed! I think the last thing to do is make provisions for a command line only installation on OSX. I'll make a start on that today.

PS I managed to get Multinest working on my PC - thanks for making that template, it was very helpful. 

Cheers,
Michael
