### ISSUE TITLE
Remove gui file picker from superplot.summary?

### ISSUE THREAD

**Issue by michaelhb** [michaelhb/superplot#26]
I am currently testing the CLI tools on OSX. super_command works fine. summary fails because it imports gui code, and subsequently crashes for the usual reasons. Two possible fixes:

a) Factor out the file chooser dialogues (i.e. remove them from super_gui) so summary can use them without hitting the problematic import (i.e. backend_gdk).

b) Remove the file pickers and replace with a CLI.

I think b) is the better option for a couple of reasons:
- If you only want the command line tools, you won't need to install GTK at all.
- Scriptability might be useful to some people.

Andrew - does this sound OK?

**Comment by michaelhb** [comment]
@innisfree

**Comment by andrewfowlie** [comment]
Hello,

Sounds great. I agree that b) is preferable to a), but option c) don't fix
the superplot_summary is also a possibility.

If it's easy ish, fix it. If not, don't bother.

**Comment by michaelhb** [comment]
All good, is done. Have also got docs building again. I think we're ready to do the release. If you're happy to go ahead let me know and I'll push the button / update RTD etc.

Cheers!

**Comment by andrewfowlie** [comment]
Hello, Yes, please go ahead! Thanks,

Andrew.

**Comment by michaelhb** [comment]
Done!

PS I tried out eggbox with KDE and it looks very slick: https://i.imgur.com/l69AtT9.png

**Comment by andrewfowlie** [comment]
Thanks. And yeah, the eggbox result looks good. I'm going to email you a draft of the paper for the arXiv/journal.
