### ISSUE TITLE
Overlaying two figures

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#31]
I had a go at overlaying two figures from their pickled objects. It's pretty bad as the their are some bugs in the pickling/unpickling (https://github.com/matplotlib/matplotlib/issues/6048) and it's really not designed to work this way.

Nevertheless, I wrote this code

https://gist.github.com/innisfree/2081657f8289bb82a0e121625affb917

which can overlay figures. it's slightly better than just merging two pdf files as you can set the alpha channel.  [Example figure:](https://github.com/michaelhb/superplot/files/626575/combined.pdf)

* Use the GUI to make 2 plots (in this case, PL filled contours, and posterior pdf with pdf checkbox unticked so you only get contours).
* Save the pickles
* python merge.py picke_1.pkl pickle_2.pkl

What do you think? It's far from ideal, but could be useful for some people.

**Comment by andrewfowlie** [comment]
I've committed the code for merging pickled files. 

I've also added an example of using superplot to make a custom plot with 2 chains shown. Running two_plots.py gives [combined.pdf](https://github.com/michaelhb/superplot/files/630017/combined.pdf).  It's obviously more complicated than using the GUI, but if you someone wants to make something specialized that's inevitable.

**Comment by michaelhb** [comment]
Looks good! I have just pushed a new release on PIP and updated the docs on RTD.

**Comment by Vital-Fernandez** [comment]
@innisfree Would you advice a similar strategy to extract the data (and format) from a pickle figure so the issue ([matplotlib/matplotlib#6048](https://github.com/matplotlib/matplotlib/issues/6048))  is avoided?

**Comment by andrewfowlie** [comment]
@Delosari no, I wouldn't. My strategy was just a hack to overlay two pickled plots. Extracting data from, formatting etc a pickled plot is tricky because of the bug https://github.com/matplotlib/matplotlib/issues/6048 that you mention.
