### ISSUE TITLE
Snippet of code for testing LaTeX

### ISSUE THREAD

**Issue by andrewfowlie** [michaelhb/superplot#6]
Here is some code for checking LaTeX options. I've written it with 3 options: no LaTeX at all (fallback to matplotlib's mathtext), LaTeX math, and LaTeX math and text. If LaTeX fails, it's turned off. I don't know whether there is a better way of testing LaTeX than this.

In the options yaml file, there should be a variable usetex which equals "math", "all" or None-type (or something equivalent, a string "never" if necessary).

```
        from matplotlib import rc
        import matplotlib.pyplot as plt
        import warnings

        usetex = "math"
        assert usetex in ["math", "all", None]

        rc('text', usetex=bool(usetex))

        if usetex:

            try:
                plt.title(r"Testing \LaTeX\ fonts and math: $\cos \theta$")
                plt.draw()  # This won't block
            except RuntimeError as error:
                warnings.warn("Cannot use LaTeX fonts. Using matplotlib's mathtext")
                print error.message
                rc('text', usetex=False)  
            else:
                if usetex is "all":
                    rc('font',**{'family':'serif', 'serif':['Computer Modern Roman']})  
```

**Comment by michaelhb** [comment]
Looks good! Will test & add tomorrow.

**Comment by michaelhb** [comment]
I've added a "usetex" option and the ability to set it to "all" "math" or "none". Checked that "none" works fine when LaTeX is uninstalled.

I didn't get a RuntimeError from "plt.title(r"Testing \LaTeX\ fonts and math: $\cos \theta$")" when LaTeX was uninstalled on my system. What I actually got was a system error from a subprocess spawned by matplotlib trying to find the 'latex' shell command. So I ended up implementing the fallback to mathtext like this:

``` python
    if usetex != "none":
        # Check if LaTeX is available.
        try:
            subprocess.call(["latex", "-version"])
        except OSError as e:
            if e.errno == os.errno.ENOENT:
                warnings.warn(
                    "Cannot use LaTeX fonts. "
                    "Using matplotlib's mathtext.")
            else:
                # Some other problem
                raise
        else:
            # Enable LaTeX
            rc('text', usetex=True)

            if usetex == "all":
                # Enable LaTeX for all text, set font
                rc('font',
                   **{'family': 'serif',
                      'serif': ['Computer Modern Roman'],
                      'size': '20'})
```

**Comment by andrewfowlie** [comment]
Great, that looks good. Funny that there isn't a python way to check for latex in matplotlib.

**Comment by andrewfowlie** [comment]
I've put in a small pull request from my fork. The code should do `rc('text', usetex=False)` if there's a problem with latex or if `usetex="none"`. This is necessary because somebody might have `usetex=True` by defaul in their rcparams, and our `usetex` parameter should override that.

**Comment by michaelhb** [comment]
Looks good to me!

I've started PEP8-ing everything in sight - I'm off to dinner now but I'll do a push some time tomorrow. Will be on a branch off refactor so we can roll back if need be.

**Comment by michaelhb** [comment]
LaTeX optional-ness and fallback when not available seems to be working fine - closing this.
